-- 02_KPI_Analysis.sql

/*
====================================================
Project: Fintech Analytics
File: 02_KPI_Analysis.sql

Objective:
Calculate core business KPIs including
revenue, fees, taxes, transaction counts,
fraud metrics, and risk metrics.

Author: Devraj Singh
====================================================
*/

-- QUESTION 1: What is the total dollar volume of transactional value processed by the platform?
-- INSIGHT: Global transaction gross volume balances to ₹455,534,249.62, showcasing high-scale market liquidity.
SELECT
    ROUND(SUM(amount),2) AS total_amount
FROM finance_transactions;


-- QUESTION 2: How much raw fee revenue was generated by platform processing clearings?
-- INSIGHT: Cumulative interchange and transaction fee captures total ₹726,242.20, forming the platform's baseline primary operating yield.
SELECT
    ROUND(SUM(fee_amount),2) AS total_fees
FROM finance_transactions;


-- QUESTION 3: What is the cumulative tax volume collected across all processed actions?
-- INSIGHT: System captured exactly ₹130,736.35 in regulatory taxes, establishing clear visibility for state compliance auditing.
SELECT
    ROUND(SUM(tax_amount),2) AS total_tax
FROM finance_transactions;


-- QUESTION 4: What is the net economic transaction value remaining after pulling out processing fees and regulatory taxes?
-- INSIGHT: Net transaction capital velocity settles at ₹454,677,271.07, proving that operational leaks (fees/taxes) stay tightly minimized.
SELECT
    ROUND(SUM(amount) - SUM(fee_amount) - SUM(tax_amount),2) AS net_transaction_value
FROM finance_transactions;


-- QUESTION 5: What is the absolute baseline count of all transaction entries logged in the system ledger?
-- INSIGHT: Total portfolio database depth sits at exactly 50,000 distinct log rows.
SELECT
    COUNT(*) AS total_transactions
FROM finance_transactions;


-- QUESTION 6: Out of the total transacting volume, how many unique customer profiles actively cleared transactions?
-- INSIGHT: Out of 5,000 master accounts, 3,983 unique consumers initiated transactions, showing an active market engagement velocity of 79.66%.
SELECT
    COUNT(DISTINCT customer_id) AS unique_customers
FROM finance_transactions;


-- QUESTION 7: What is the baseline Average Transaction Value (ATV) managed across the platform?
-- INSIGHT: Normal ticket size settles at ₹9,110.68, confirming a mid-to-high ticket financial distribution network.
SELECT
    ROUND(AVG(amount),2) AS avg_transaction_value
FROM finance_transactions;


-- QUESTION 8: What is the average operational transaction fee charged per individual transaction instance?
-- INSIGHT: The average cost per action stands at ₹14.52, giving product teams a steady metric to evaluate corporate pricing strategies.
SELECT
    ROUND(AVG(fee_amount),2) AS avg_fee
FROM finance_transactions;


-- QUESTION 9: What is the average regulatory tax impact processed per separate transaction event?
-- INSIGHT: The normalized tax cost settles at ₹2.61 per transaction ticket line.
SELECT
    ROUND(AVG(tax_amount),2) AS avg_tax
FROM finance_transactions;


-- QUESTION 10: What is the baseline success rate percentage across all processed transaction logs?
-- INSIGHT: Platform clears a strong 85.74% success rate, proving high processing architecture reliability.
-- TECHNICAL NOTE: Utilizes explicit FILTER clauses for elegant conditional aggregation over old CASE WHEN structures.
SELECT
    ROUND(COUNT(*) FILTER(WHERE transaction_status = 'Success') * 100.0 / COUNT(*),2) AS success_rate_pct
FROM finance_transactions;


-- QUESTION 11: What percentage of total transaction volume resulted in processing failures?
-- INSIGHT: Financial system failure leakage sits at 10.19%, highlighting a key point for clearing network diagnostics.
SELECT
    ROUND(COUNT(*) FILTER(WHERE transaction_status = 'Failed') * 100.0 / COUNT(*),2) AS failed_rate_pct
FROM finance_transactions;


-- QUESTION 12: What percentage of transaction entries are currently held in a pending reconciliation loop?
-- INSIGHT: Settlement lag remains low with only 4.07% of the ledger in a pending status.
SELECT
    ROUND(COUNT(*) FILTER(WHERE transaction_status = 'Pending') * 100.0 / COUNT(*),2) AS pending_rate_pct
FROM finance_transactions;


-- QUESTION 13: What is the absolute count of verified fraudulent entries caught inside the active portfolio ledger?
-- INSIGHT: Risk operations flagged exactly 630 explicitly fraudulent transaction attempts.
SELECT
    COUNT(*) AS fraud_transactions
FROM finance_transactions
WHERE is_fraud = 'Yes';


-- QUESTION 14: What is the cumulative financial capital volume exposed to verified fraud instances?
-- INSIGHT: Exposed capital leak balances to ₹5,969,443.52, serving as a critical metric for chargeback liability provisions.
SELECT
    ROUND(SUM(amount),2) AS fraud_amount
FROM finance_transactions
WHERE is_fraud = 'Yes';


-- QUESTION 15: What is the relative fraud incidence percentage rate across the entire global transaction volume?
-- INSIGHT: Global bad-actor fraud levels stay contained at 1.26%, validating effective real-time security model rules.
SELECT
    ROUND(COUNT(*) FILTER(WHERE is_fraud = 'Yes')* 100.0/ COUNT(*),2) AS fraud_rate_pct
FROM finance_transactions;


-- QUESTION 16: What is the overall average risk score index across the active transactional network?
-- INSIGHT: Portfolio-wide risk holds at a safe, moderate average value of 36.08 on a 1-100 index scale.
SELECT
    ROUND(AVG(risk_score),2) AS avg_risk_score
FROM finance_transactions;


-- QUESTION 17: How many total individual transactions breached high-risk operational profiles (>70)?
-- INSIGHT: Identified 517 transactions crossing critical risk boundaries, providing risk teams with a refined list for automated compliance screening.
SELECT
    COUNT(*) AS high_risk_transactions
FROM finance_transactions
WHERE risk_score > 70;


-- QUESTION 18: What percentage proportion of total portfolio volume represents a severe high-risk threat (>70)?
-- INSIGHT: Critical risk exposure is well-controlled, tracking at just 1.03% of all processed actions.
SELECT
    ROUND(COUNT(*) FILTER(WHERE risk_score > 70) * 100.0/ COUNT(*),2) AS high_risk_pct
FROM finance_transactions;


-- QUESTION 19: What is the exact macro percentage contribution ratio of processing fees relative to global transaction value?
-- INSIGHT: Direct operational fees account for 0.16% of gross value volume, highlighting an asset-light, scalable business model.
SELECT
    ROUND(SUM(fee_amount) * 100.0 / SUM(amount),2) AS fee_contribution_pct
FROM finance_transactions;


-- QUESTION 20: What is the macro percentage contribution ratio of collected taxes relative to global transaction value?
-- INSIGHT: Tax-driven fiscal collection represents 0.03% of total portfolio value velocity.
SELECT
    ROUND(SUM(tax_amount) * 100.0 / SUM(amount),2) AS tax_contribution_pct
FROM finance_transactions;

================================================================================================================================

