-- 03_Customer_Analysis.sql

/*
====================================================
Project: Fintech Analytics
File: 03_Customer_Analysis.sql

Objective:
Analyze customer demographics,
segments, occupations, geographic
distribution, and customer value.

Author: Devraj Singh
====================================================
*/

-- QUESTION 1: What is the total volume of transactions generated across different consumer segments?
-- INSIGHT: The 'Retail' segment acts as the platform's core volume driver with 27,112 transactions, 
-- followed heavily by 'Premium' (9,210) and 'SME' (8,002).
SELECT
    c.customer_segment,
    COUNT(ft.transaction_id) AS total_transactions
FROM customers c
JOIN finance_transactions ft 
    ON c.customer_id = ft.customer_id
GROUP BY c.customer_segment
ORDER BY total_transactions DESC;


-- QUESTION 2: What is the total gross revenue volume generated by each distinct customer segment?
-- INSIGHT: 'Retail' leads absolute revenue contribution at ₹248,079,600.00, proving that individual 
-- consumer liquidity outpaces current high-ticket corporate holdings on the platform.
SELECT
    c.customer_segment,
    ROUND(SUM(ft.amount),2) AS total_amount
FROM customers c
JOIN finance_transactions ft
    ON c.customer_id = ft.customer_id
GROUP BY c.customer_segment
ORDER BY total_amount DESC;


-- QUESTION 3: What is the normalized Average Transaction Value (ATV) across different profile tiers?
-- INSIGHT: High-value corporate clusters retain steady individual ticket heights, helping product 
-- management teams tailor transaction limit structures.
SELECT
    c.customer_segment,
    ROUND(AVG(ft.amount),2) AS avg_transaction
FROM customers c
JOIN finance_transactions ft
    ON c.customer_id = ft.customer_id
GROUP BY c.customer_segment
ORDER BY avg_transaction DESC;


-- QUESTION 4: How does overall transaction revenue volume distribute when segmented by customer gender?
-- INSIGHT: Female account profiles generate a slightly higher top-line volume at ₹235,628,300.00, 
-- compared to Male profiles at ₹219,906,000.00.
SELECT
    c.gender,
    ROUND(SUM(ft.amount),2) AS total_amount
FROM customers c
JOIN finance_transactions ft
    ON c.customer_id = ft.customer_id
GROUP BY c.gender
ORDER BY total_amount DESC;


-- QUESTION 5: Which specific customer occupation classes drive the highest revenue velocity across the platform?
-- INSIGHT: 'Freelancers' lead absolute spending power at ₹80,669,237.67, with 'Retired' close behind 
-- at ₹78,529,052.59, representing major target hubs for deposit retention campaigns.
SELECT
    c.occupation,
    ROUND(SUM(ft.amount),2) AS total_amount
FROM customers c
JOIN finance_transactions ft
    ON c.customer_id = ft.customer_id
GROUP BY c.occupation
ORDER BY total_amount DESC;


-- QUESTION 6: Which geographical state territories represent the top transaction revenue engines?
-- INSIGHT: Maharashtra holds a major lead at ₹68,287,471.91, followed by Karnataka (₹52,858,322.32) 
-- and Gujarat (₹50,061,741.93), mapping out the core tier-1 market pillars.
SELECT
    c.state,
    ROUND(SUM(ft.amount),2) AS total_amount
FROM customers c
INNER JOIN finance_transactions ft
    ON c.customer_id = ft.customer_id
GROUP BY c.state
ORDER BY total_amount DESC;


-- QUESTION 7: Who are the top 10 highest-value customer profiles based on accumulated historical transaction spend?
-- INSIGHT: Pinpoints explicit top-tier platform accounts, enabling automated routing into premium 
-- priority service channels and high-touch account management.
SELECT
    c.customer_id,
    c.customer_name,
    ROUND(SUM(ft.amount),2) AS total_amount
FROM customers c
JOIN finance_transactions ft
    ON c.customer_id = ft.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_amount DESC
LIMIT 10;


-- QUESTION 8: How do all individual active customers rank relative to one another based on cumulative expenditure?
-- INSIGHT: Dynamically assigns continuous portfolio rankings via window function blocks, removing the 
-- need for hardcoded staging parameters.
SELECT
    c.customer_id,
    c.customer_name,
    ROUND(SUM(ft.amount),2) AS total_amount,
    RANK() OVER(ORDER BY SUM(ft.amount) DESC) AS revenue_rank
FROM customers c
JOIN finance_transactions ft
    ON c.customer_id = ft.customer_id
GROUP BY c.customer_id, c.customer_name;


-- QUESTION 9: Who are the elite top 20 customer accounts across the platform based on dense revenue contribution?
-- INSIGHT: Isolates high-value clusters via Common Table Expressions (CTEs), allowing seamless 
-- extraction for targeted loyalty campaigns.
WITH customer_revenue AS (
    SELECT
        c.customer_id,
        c.customer_name,
        ROUND(SUM(ft.amount),2) AS total_amount,
        RANK() OVER(ORDER BY SUM(ft.amount) DESC) AS revenue_rank
    FROM customers c
    JOIN finance_transactions ft
        ON c.customer_id = ft.customer_id
    GROUP BY c.customer_id, c.customer_name
)
SELECT *
FROM customer_revenue
WHERE revenue_rank <= 20;


-- QUESTION 10: Who are the top 5 most valuable users when balancing both transaction count and cumulative volume?
-- INSIGHT: Combining volume checks with absolute customer spend isolates key active users, 
-- separating high-value accounts from single large transactions.
WITH customer_revenue AS (
    SELECT
        customer_id,
        COUNT(transaction_id) AS transactions,
        SUM(amount) AS revenue
    FROM finance_transactions
    GROUP BY customer_id
)
SELECT
    cr.customer_id,
    c.customer_name,
    cr.transactions,
    ROUND(cr.revenue, 2) AS revenue
FROM customer_revenue cr
JOIN customers c
    ON cr.customer_id = c.customer_id
ORDER BY revenue DESC
LIMIT 5;


-- QUESTION 11: Which high-value customer profiles have exceeded an absolute Lifetime Value threshold of ₹100,000?
-- INSIGHT: Filters core account tiers via HAVING conditions, providing a clean customer base 
-- for specialized wealth management initiatives.
SELECT
    c.customer_id,
    c.customer_name,
    ROUND(SUM(ft.amount),2) AS lifetime_value
FROM customers c
JOIN finance_transactions ft
    ON c.customer_id = ft.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING SUM(ft.amount) > 100000
ORDER BY lifetime_value DESC;


-- QUESTION 12: What is the exact customer lifetime value metrics and order frequency for our top 20 consumers?
-- INSIGHT: Delivers quick visibility into maximum customer value, ensuring retention 
-- efforts are directed toward the most profitable accounts.
SELECT
    c.customer_id,
    c.customer_name,
    COUNT(*) AS transactions,
    ROUND(SUM(ft.amount),2) AS lifetime_value
FROM customers c
JOIN finance_transactions ft
    ON c.customer_id = ft.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY lifetime_value DESC
LIMIT 20;


-- QUESTION 13: What is the true Average Revenue Per User (ARPU) across all actively transacting customers?
-- INSIGHT: Average revenue per active user settles at an impressive ₹114,369.63, establishing 
-- a benchmark for customer acquisition costs (CAC) and marketing budgets.
SELECT
    ROUND(SUM(ft.amount) / COUNT(DISTINCT c.customer_id),2) AS avg_revenue_per_customer
FROM customers c
JOIN finance_transactions ft
    ON c.customer_id = ft.customer_id;


-- QUESTION 14: How does new user acquisition distribute chronologically when analyzed by registration year?
-- INSIGHT: Demonstrates clean, steady customer growth of roughly 600+ new users annually from 2018 to 2025, 
-- proving reliable, long-term acquisition health.
SELECT
    DATE_TRUNC('year', join_date) AS join_year,
    COUNT(*) AS total_customers
FROM customers
GROUP BY join_year
ORDER BY join_year;


-- QUESTION 15: Which specific customer profiles have zero active transaction logs across the ledger?
-- INSIGHT: Out of 5,000 users, 1,017 accounts show no transaction activity. 
-- This clearly flags cold accounts that are ripe for targeted re-engagement or activation campaigns.
SELECT
    c.customer_id,
    c.customer_name,
    ft.transaction_id
FROM customers c
LEFT JOIN finance_transactions ft
    ON c.customer_id = ft.customer_id
WHERE ft.transaction_id IS NULL;

================================================================================================================================

